var keywords = [
  "Help",
  "Support",
  "Assistance",
  "Chat",
  "Contact",
  "Live chat",
  "Customer service",
  "Technical issue",
  "Problem",
  "Troubleshoot",
  "Error",
  "Query",
  "Talk to an agent",
  "Need help",
  "Chat support",
  "Talk to support",
  "Online help",
  "Ask for help",
  "Report an issue",
  "Speak to a representative",
  "Get assistance",
  "Request support",
  "Live support",
  "Chat with a representative",
  "Contact us",
  "Support chat",
  "Help desk",
  "Assist",
  "Talk to a live person",
  "Support team",
  "Help center",
  "Contact customer support",
  "Technical problem",
  "Customer care",
  "Talk to someone",
  "Trouble",
  "Issue",
  "Chat assistance",
  "Get help",
  "Chat with support",
  "Contact help",
  "Chat help",
  "Reach support",
  "Support chatbot",
  "Customer service chat",
  "Need assistance",
  "Support contact",
  "Help chat",
  "Connect with support",
  "Support representative",
  "Assistance chat",
]
